server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: a-service
          uri: lb://a-service
          order: 100
          predicates:
            - Path=/getA/**
        - id: b-service
          uri: lb://b-service
          order: 100
          predicates:
            - Path=/getB/**